lat_mpc:
  N: 20
  dt: 0.1
  wheelbase: 2.85
  max_steer_deg: 35.0
  q_ey: 4.0
  q_eyaw: 0.9
  R_delta: 0.5
  R_ddelta: 2.0
  ddelta_max_deg: 5.0

leader_lon_pid:
  kp: 0.95
  ki: 0.05
  kd: 0.00
  a_limit: 1.5
  i_limit: 1.0

follower_lon_mpc: {}